### ISSUE TITLE
Fails to remove unnecessary packages

### ISSUE THREAD

**Issue by PhilPJL** [twsouthwick/NuGetPackageConfigConverter#21]
### Installed product versions
- Visual Studio: [2017 Ent 15.4.2]
- This extension: [0.1.30]
- Project types within the solution being converted: Single .NET class library

### Description
Fails to remove unnecessary packages

### Steps to recreate
Create a single class library.  Reference DocumentFormat.OpenXml using packages.config.  Update all packages.  We end up with 49 packages referenced!

Create a single class library.  Reference DocumentFormat.OpenXml using package references.  Update all packages.  We end up with 1 package referenced.

Update the first project to use package references.  I expected all the unnecessary package refs to be removed.  They aren't.

**Comment by twsouthwick** [comment]
This is by design, unfortunately. Using packages.config brings in all transitive references. This tool is only designed to convert packages you referenced to to PackageReferences. I would be happy for a PR, but it is not trivial work. It's easy enough, though, to go through the resulting PackageReferences and remove the entries you don't need.

**Comment by twsouthwick** [comment]
This project will not be maintained as support for converting to PackageReference is included in VS 15.7+: https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
