### ISSUE TITLE
It removes the content in ApplicationInsight.config

### ISSUE THREAD

**Issue by Itfly** [twsouthwick/NuGetPackageConfigConverter#24]
After running Update to Package References, the content in ApplicationInsight.config also be removed. I have to manually checkout these changes,

**Comment by Itfly** [comment]
It also remove some items in web.config

**Comment by twsouthwick** [comment]
This is probably because NuGet no longer honors Content with PackageReference, so it gets removed when removing the NuGet files and then doesn't get added back. Do you have a repro? The minimal need to make a repro would be a list of NuGet packages and the project type. If this is OSS, you can share a link and I'll take a look, otherwise, I'll need the lists.

**Comment by Itfly** [comment]
Sorry, this repro is not oss. Which lists do you need?

**Comment by Itfly** [comment]
BTW, it does not remove the Reference like below:
 ```
<Choose>
    <When Condition="'$(VisualStudioVersion)' == '10.0' And '$(IsCodedUITest)' == 'True'">
      <ItemGroup>
        <Reference Include="Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Common, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Extension, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITesting, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```

**Comment by twsouthwick** [comment]
I need the contents of `packages.config` and the project type to repro the issue.

As for your other comment, it doesn't remove those testing assemblies by design - those are not NuGet packages brought in by `packages.config`. They're stored in the GAC I believe. You can remove them and switch them to the MSTest NuGet packages, but that's beyond the scope of this project which is to convert packages brought in by `packages.config` to the newer `PackageReference` format

**Comment by Itfly** [comment]
I just sent it to you.
Thanks

**Comment by twsouthwick** [comment]
Looks like this is due to the Microsoft.ApplicationInsights.Web package. Unfortunately, this is a side effect of the deprecation of `content` in favor of `contentFiles` by NuGet. Please note that when the conversion completes it lets you know that some files may have been removed - precisely because of this. I assume projects are under source control, and the files needed can just be reverted back and become a file in the project independent of the package. 

There's not much I can do without hacking a list of files to retain. Some packages may not be compatible with PackageReference (see https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations for some documentation)
